### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by jumpingfox27** [khang06/PianoFromAbove#11]
i don't know if i'm doing anything wrong and where i should ask for help, but i get a bunch of errors when i try to build
i tried following the steps in the README.md

and i also don't know how i should show it so
here are all of the errors i get, and some of them show multiple times, most of them are from Renderer.cpp:
```
invalid type used for 'SV_VertexID' input semantics, must be integral - background_vs.hlsl (line 3)
expected a comma (the one-argument version of static_assert is not enabled in this mode) - Renderer.h (line 59)
name followed by '::' must be a class or namespace name - Renderer.cpp (lines 1385, 1376, 1021)
expected an expression - Renderer.cpp (takes up like 90% of the error list, the last 5 lines were 1355, 1354, 1353, 1268, 1267)
no instance of overloaded function "std::get" matches the argument list - Renderer.cpp (lines 860, 859, 622)
namespace "std" has no member "make_tuple" - Renderer.cpp (shows up multiple times, the last 3 lines were 849, 829, 801)
function "D3D12Renderer::CreateWindowDependentObjects" returns incomplete type "std::tuple<HRESULT, const char *>" - Renderer.cpp (line 640)
function "D3D12Renderer::Init" returns incomplete type "std::tuple<HRESULT, const char *>" - Renderer.cpp (line 44)
#error directive: WRL requires NTDDI_VERSION to be #defined at least to NTDDI_VISTA or greater - def.h (line 48)
class "Microsoft::WRL::Details::EnableIf<false, void *>" has no member "type" - client.h (line 445)
cannot open source file "Config.h" - Renderer.cpp (line 24)
```
and i also get 3 warnings, but i don't know if they do anything:
```
WRL requires NTDDI_VERSION to be #defined at least to NTDDI_VISTA or greater - def.h (line 48)
'Config.h' file not found with <angled> include; use "quotes" instead - RENDERER.CPP (line 24)
non-constant-expression cannot be narrowed from type 'unsigned long long' to 'SIZE_T' (aka 'unsigned long') in initializer list - RENDERER.CPP (line 1268)
```

there are 228 errors when i try build
the "expected an expression" thing takes me to red underlined (i think it means error) dots, and there is nothing before them

**Comment by khang06** [comment]
the readme is slightly outdated and you should be using vs2022 instead of 2019, but that's about it. not really sure how these errors are happening because they suggest something is very wrong with the build configuration. can you send a screenshot of your visual studio with the project open?

**Comment by jumpingfox27** [comment]
when i run it on vs2022, theres only one error shown: "invalid type used for 'SV_VertexID' input semantics, must be integral"
first screenshot is vs2022 and second screenshot is vs2019
![image_2024-12-15_155746835](https://github.com/user-attachments/assets/d9a98099-2ffa-4cc1-8468-64f25a628ae9)
![image_2024-12-15_155802190](https://github.com/user-attachments/assets/e2cdf7ed-00ae-438d-9f1e-f9448bf166cf)

**Comment by khang06** [comment]
oh, building for 32-bit is unsupported. you should change the build configuration to compile for Release x64

**Comment by jumpingfox27** [comment]
it says:

cannot open include file 'afxres.h'.
in PianoFromAbove.rc

**Comment by jumpingfox27** [comment]
i fixed the afxres.h and IT SHOWS THE WINDOW!!! but, it's a white screen that does nothing

edit: nevermind, it works correctly, its just that vs2022 froze for a few seconds
