### ISSUE TITLE
make 'invisible PFA on start' an optional option

### ISSUE THREAD

**Issue by rin-w** [khang06/PianoFromAbove#7]
there is this surprise feature in PFA since the beginning of its conception where when you wake up in morning and decide you will listen to black midi, but then when you first open it, it suddenly doesn't appear and just sits on the taskbar, playing the black midi international anthem.

<details>
  <summary>review for activating the feature</summary>

1. open pfa
2. maximise pfa
3. minimise pfa
4. close pfa by hovering cursor on taskbar pfa icon
5. reopen pfa
    
   credits: steps by ymiblackmoon
  </details>
</details>

the methods to stop enjoying this feature temporarily is either by maximizing its window through the taskbar preview then restarting the app, or by force closing PFA then resetting the `Config.xml` file.

i believe making this feature optional will make the revolutionists and conservatives of PFA agree to each other. and if they still want this possibly deprecated feature to randomly surprise them, they can do so by enabling it in the settings.

**Comment by khang06** [comment]
stock pfa purists are free to use https://github.com/khang06/notviz if they want their windows to spawn sqrt(32000^2+32000^2) pixels offscreen
