### ISSUE TITLE
Stuck on sorting events

### ISSUE THREAD

**Issue by GreenWeegeeCantCode** [khang06/PianoFromAbove#9]
When i try to play a midi, it just says sorting events and thats it.

![image](https://github.com/khang06/PianoFromAbove/assets/145769578/d29e7347-64e8-4e56-8e36-09e1dc84d0f3)

**Comment by khang06** [comment]
disable ffmpeg mode if you have it on

**Comment by GreenWeegeeCantCode** [comment]
alright thanks
